backend:
  name: github
  repo: kamori-web/watoto-fashions
  branch: main
  base_url: https://api.github.com
  auth_endpoint: https://github-oauth-login.netlify.app

media_folder: "images"
public_folder: "/images"

collections:
    - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Price", name: "price", widget: "number"}
            - {label: "Image", name: "image", widget: "image"}
            - {label: "Category", name: "category", widget: "string"}
            - {label: "Description", name: "body", widget: "markdown"}
