backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
    - name: "products"
    label: "Nguo za Watoto"
    folder: "content/products"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
            - {label: "Jina ya Nguo", name: "title", widget: "string"}
            - {label: "Bei KSh", name: "price", widget: "number"}
            - {label: "Picha", name: "image", widget: "image"}
            - {label: "Category", name: "category", widget: "select", options: ["Jerseys", "Dresses", "Tracksuits", "Shoes", "Newborn"]}
            - {label: "Size/Age", name: "size", widget: "string", default: "2-3 years"}
            - {label: "Location", name: "location", widget: "string", default: "Thika Town"}